### ISSUE TITLE
trouble when testing live555

### ISSUE THREAD

**Issue by songxpu** [bajinsheng/SFuzzer#1]
Hi ,
I am insterested in this work, and I hvae tried to use it to fuzz live555 , but I met some trouble.

Firstly, I change testOnDemandRTSP.cpp main function ,like :
```bash
sed -i "s/ main/  HonggfuzzNetDriver_main/g" testProgs/testOnDemandRTSPServer.cpp
```
as u can see :
![image](https://user-images.githubusercontent.com/44093631/173612361-4969458d-5cd5-4cd6-94f4-2fec697b3d17.png)

Then , I build the project with `-fsanitize=fuzzer-no-link -fsanitize=address` 

Finally ,the compilation will fail at the final link stage, I add "-lsFuzzer -lhfnetdriver -lhfcommon" like openssl example in your project ,but I still fail , just like :
![image](https://user-images.githubusercontent.com/44093631/173613160-d7f67c05-1973-4fa6-9556-878ba7221d51.png)

I hvae already changed main to HonggfuzzNetDriver_main, so really confused.

Can you help me or provide your operation process?

**Comment by bajinsheng** [comment]
It is probably because of the lack of ```extern C```.
The Live555 is written in CPP, while our interface is written in C, so it may need ```extern C``` when linking CPP projects.
```shell
sed -i "s/int main(/extern \"C\" int HonggfuzzNetDriver_main(/g" testProgs/testOnDemandRTSPServer.cpp
```

**Comment by songxpu** [comment]
> It is probably because of the lack of `extern C`. The Live555 is written in CPP, while our interface is written in C, so it may need `extern C` when linking CPP projects.
> 
> ```shell
> sed -i "s/int main(/extern \"C\" int HonggfuzzNetDriver_main(/g" testProgs/testOnDemandRTSPServer.cpp
> ```

Hi, I build the program successfully with your help, thank u so much.

But when I run it , the speed is too slow and even pause in some time.

I run the following command both in root and normal user, the outcome same.

```bash
./testOnDemandRTSPServer ./in/
```

![image](https://user-images.githubusercontent.com/44093631/173718948-c15fb06b-4c46-4115-a023-6f8ebbe28f90.png)

I am not sure which step is wrong.

**Comment by songxpu** [comment]
After for one or two minutes, I got the following hint info ,it seem that the server may not restart successfully and so fuzzer timeout.

![image](https://user-images.githubusercontent.com/44093631/173719576-10fe2b40-54cd-4493-a8e9-03450d719258.png)

**Comment by bajinsheng** [comment]
The port used by Live555 is 8554, so you should set the env:  ```HFND_TCP_PORT=8554```

The network protocol programs are significantly affected by the environment, so it is better to run it in an isolated env, such as docker.

I will push my scripts for running Live555 this weekend.

**Comment by songxpu** [comment]
> HFND_TCP_PORT=8554

In fact , I have set env :HFND_TCP_PORT=8554, maybe the enviroment is something wrong as u mentioned.

Thank you so much ,I am looking forward to your update for live555 project, It may help me a lot .

: )

**Comment by songxpu** [comment]
Hi, I build live555 successfully by the docker, and I met some new trouble.
That is sgfuzz would stop running after finding a crash , I add `ignore crash` , but no change here.
So how to make sgfuzz fuzz until I shut it down.
The following is my command:
```bash
./testOnDemandRTSPServer -close_fd_mask=3 -print_final_stats=1 -ignore_crashes=1 -ignore_timeouts=1 -ignore_ooms=1 -timeout=3 -detect_leaks=0 -dict=./rtsp.dict -only_ascii=1 ./corpus
```

**Comment by songxpu** [comment]
After consulting relevant documents, I found the option `-fork=N` of libfuzzer. It solved the problem, but I am not sure whether it influent sgfuzz performance or other things.

Like the following command:
```bash
./testOnDemandRTSPServer -close_fd_mask=3 -print_final_stats=1 -fork=1 -ignore_crashes=1 -ignore_timeouts=1 -ignore_ooms=1 -timeout=3 -detect_leaks=0 -dict=./rtsp.dict -only_ascii=1 ./corpus
```

**Comment by bajinsheng** [comment]
Although it is able to run with `-fork=N`, we don't support the fork mode, which may mess up our state tracing.

This is no easy way to ignore the crash.
What we did is to manually review the source code of live555 and block the crash.
