### ISSUE TITLE
testing OpenSSL old ver.

### ISSUE THREAD

**Issue by zyyzii** [bajinsheng/SFuzzer#3]
Hi , I've been interested in this work. To extend it I tried to use it to fuzz older version of OpenSSL, like openssl 1.1.0, 1.0.1. 

But I found that the coverage begins with 20+ and after one-day fuzzing it only came to 40+. While the coverage of fuzzing 3.0.0 and 1.1.1 begins with 4000+. 

I tried to modify compilation options and other approaches but I couldn't fix this trouble. So, I'm writing this issue to see if you've countered this kind of problem and know what's wrong with it.

**Comment by bajinsheng** [comment]
It is likely because the old version of OpenSSL is not correctly executed, not only the compilation options.
Perhaps you can use gdb to step into the execution and check where the process exits.
