### ISSUE TITLE
DTLS in OpenSSL

### ISSUE THREAD

**Issue by hey3e** [bajinsheng/SFuzzer#4]
I've studied this project on OpenSSL. It's cool that it can cover so many states. While I found that it can not fuzz the DTLS over OpenSSL. Is there a way to achieve that?

**Comment by bajinsheng** [comment]
Can you give more information about why cannot test? If you do not know how to your own targets, please see these [tutorials](https://github.com/bajinsheng/SGFuzz/tree/master/example).

**Comment by hey3e** [comment]
I followed the tutorial and it worked on OpenSSL, while I found that it seems like SGFuzz can not cover the DTLS related state like DTLS_ST_SW_HELLO_VERIFY_REQUEST.

**Comment by bajinsheng** [comment]
Unfortunately, I did this experiment around two years ago, and cannot remember every detail. I guess it is likely because of specific switches in configuration files and specific tested binary files in OpenSSL.

**Comment by hey3e** [comment]
Okay! Thanks.
