### ISSUE TITLE
SGFuzz on mbedtls

### ISSUE THREAD

**Issue by hey3e** [bajinsheng/SFuzzer#6]
I'm trying to apply SGFuzz to other targets like mbedtls.

Some main commands are as follow:

`sed -i "s/ main/ HonggfuzzNetDriver_main/g" '/SGFuzz-evaluation/SGFuzz/mbedtls/programs/ssl/ssl_server2.c'`

`make CC=clang-10 CXX=clang++-10 CFLAGS="-fsanitize=fuzzer-no-link -fsanitize=address" -lsFuzzer -lhfnetdriver -lhfcommon`

While during the link stage, error occurs:

`  CC    ssl/ssl_server2.c
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crt1.o：In function ‘_start’：
(.text+0x20)：undefined reference to ‘main’
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:359: recipe for target 'ssl/ssl_server2' failed
make[1]: *** [ssl/ssl_server2] Error 1
Makefile:15: recipe for target 'programs' failed
make: *** [programs] Error 2`

**Comment by bajinsheng** [comment]
I think `-lsFuzzer -lhfnetdriver -lhfcommon` parameters are required to be passed to linker, such as `clang`, not `make`

**Comment by hey3e** [comment]
Still not work.

My whole workflow:

1. Build SGFuzz and honggfuzz.
2. git clone mbedtls.
3. `sed -i "s/ main/ HonggfuzzNetDriver_main/g" ./mbedtls/programs/ssl/ssl_server2.c`
4. state instrumentation.
5. `make CC=clang-12 CXX=clang++-12 CFLAGS="-fsanitize=fuzzer-no-link -fsanitize=address -lsFuzzer -lhfnetdriver -lhfcommon" LDFLAGS="-fsanitize=fuzzer-no-link -fsanitize=address"`

I saw your paper evaluated MbedTLS, I wonder if you could kindly help me understand if I might have made any errors in my assessment.

**Comment by bajinsheng** [comment]
You can check your detailed compiling commands during the `make` execution and see why the library is not found during linking.

My experiments on MbedTLS were based on Fuzzbench, not in this way, so I do not have the script to manually compile mbedtls.
https://github.com/bajinsheng/SGFuzz_Fuzzbench

**Comment by hey3e** [comment]
I turned to FuzzBench to evaluate and I met this problem:

![image](https://github.com/bajinsheng/SGFuzz/assets/89211406/27336fa5-dbc6-4568-a929-26981555cdb3)

**Comment by mboehme** [comment]
Looks like a problem in FuzzBench. Can you sync your fork with FuzzBench current branch and try again?
