### ISSUE TITLE
Capturing request and resposes.

### ISSUE THREAD

**Issue by behnamben** [bajinsheng/SFuzzer#8]
I'm trying to capture the requests and responses from the fuzzing target while I am running SGFuzz. I tried using Wireshark but it seems like I was wrong. How can I do this?

**Comment by bajinsheng** [comment]
What targets and benchmarks are you running? For [Fuzzbench](https://github.com/bajinsheng/SGFuzz_Fuzzbench), SGFuzz directly pass the inputs to target programs via fuzzing harnesses instead of  socket. If you run SGFuzz by [netdriver](https://github.com/google/honggfuzz/blob/master/libhfnetdriver/netdriver.c#L131), there should be a socket connection.

**Comment by behnamben** [comment]
For the ones using netdriver, whats the easiest way to capture request and responses? 
I also have a problem building the SGFuzz_Fuzzbench. So, I copied the sfuzzer folder to fuzzers folder inside fuzzbench and tried to build it. Is there something Im missing here? Im getting build errors.

**Comment by behnamben** [comment]
I also have the problem building the SGFuzz_Fuzzbench. I copied the sfuzzer folder to fuzzers folder inside fuzzbench and tried to build it. However I get: `=> ERROR [stage-1 13/15] RUN export CHECKOUT_COMMIT=$(cat /benchmark.yaml | tr -d ' ' | grep 'commit:' | cut -d ':' -f2) &&     python3 -u /opt/f  0.4s
------
 > importing cache manifest from gcr.io/fuzzbench/builders/sfuzzer/h2o_h2o-fuzzer-http2:
------
------
 > [stage-1 13/15] RUN export CHECKOUT_COMMIT=$(cat /benchmark.yaml | tr -d ' ' | grep 'commit:' | cut -d ':' -f2) &&     python3 -u /opt/fuzzbench/checkout_commit.py $CHECKOUT_COMMIT /src:
0.274 python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by python3)
0.274 python3: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by python3)
0.274 python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by python3)
0.274 python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by python3)
0.274 python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by python3)
0.274 python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by python3)
`

**Comment by bajinsheng** [comment]
> For the ones using netdriver, whats the easiest way to capture request and responses?

I have not tried to capture the traffic. If you cannot observe it by Wireshark, an alternative way is to modify the netdriver file to save the traffic to some files.

>  I copied the sfuzzer folder to fuzzers folder inside fuzzbench

You do not need to manually copy SGFuzz, which should be ready to use at https://github.com/bajinsheng/SGFuzz_Fuzzbench. I also received some feedback that there are some build errors. It is probably because Fuzzbench has some updates, which you may need to merge into the SGFuzz fork of FuzzBench.

**Comment by behnamben** [comment]
In "/example/open-ssl/Readme.md, line 93" you said "cd experiment/openssl-sfuzzer". However, there is no folder in the repo named "experiment". Maybe its related to the Fuzzbench?!

**Comment by bajinsheng** [comment]
No. It refers to the directory in the docker: https://github.com/bajinsheng/SGFuzz/blob/master/example/openssl/Dockerfile#L59

**Comment by behnamben** [comment]
In the last step of building openssl for fuzzing using SGFuzz I get the following error and I dont really know whats wrong.

/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
/lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::PrintStats(char const*, char const*, unsigned long, unsigned long)':
FuzzerLoop.cpp:(.text+0x13f0): undefined reference to `fuzzer::SM_num'
/usr/bin/ld: FuzzerLoop.cpp:(.text+0x1407): undefined reference to `fuzzer::SM_root'
/usr/bin/ld: FuzzerLoop.cpp:(.text+0x140f): undefined reference to `fuzzer::StateMachine::get_num_leaves()'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)':
FuzzerLoop.cpp:(.text+0x1a6b): undefined reference to `fuzzer::SM_added_states'
/usr/bin/ld: FuzzerLoop.cpp:(.text+0x1ae6): undefined reference to `fuzzer::SM_visited_states'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)':
FuzzerLoop.cpp:(.text+0x225f): undefined reference to `fuzzer::SM_reset()'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::MutateAndTestOne()':
FuzzerLoop.cpp:(.text+0x2e7a): undefined reference to `fuzzer::SM_visited_states'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::InputCorpus::AddToCorpus(std::vector<unsigned char, fuzzer::fuzzer_allocator<unsigned char> > const&, unsigned long, bool, bool, bool, std::chrono::duration<long, std::ratio<1l, 1000000l> >, std::vector<unsigned int, fuzzer::fuzzer_allocator<unsigned int> > const&, fuzzer::DataFlowTrace const&, fuzzer::InputInfo const*, unsigned long)':
FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm[_ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm]+0x1a3): undefined reference to `fuzzer::SM_visited_states'
/usr/bin/ld: FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm[_ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm]+0x1c4): undefined reference to `fuzzer::SM_added_states'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::InputCorpus::UpdateCorpusDistribution(fuzzer::Random&)':
FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE[_ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE]+0x23a): undefined reference to `fuzzer::SM_root'
/usr/bin/ld: FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE[_ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE]+0x242): undefined reference to `fuzzer::StateMachine::sum_hits()'
/usr/bin/ld: FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE[_ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE]+0x252): undefined reference to `fuzzer::SM_num'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by behnamben** [comment]
In the last step of making openssl for fuzzing using SGFuzz (Link SGFuzz) I get the error below and I dont really know how to solve it. 
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
/lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::PrintStats(char const*, char const*, unsigned long, unsigned long)':
FuzzerLoop.cpp:(.text+0x13f0): undefined reference to `fuzzer::SM_num'
/usr/bin/ld: FuzzerLoop.cpp:(.text+0x1407): undefined reference to `fuzzer::SM_root'
/usr/bin/ld: FuzzerLoop.cpp:(.text+0x140f): undefined reference to `fuzzer::StateMachine::get_num_leaves()'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)':
FuzzerLoop.cpp:(.text+0x1a6b): undefined reference to `fuzzer::SM_added_states'
/usr/bin/ld: FuzzerLoop.cpp:(.text+0x1ae6): undefined reference to `fuzzer::SM_visited_states'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)':
FuzzerLoop.cpp:(.text+0x225f): undefined reference to `fuzzer::SM_reset()'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::Fuzzer::MutateAndTestOne()':
FuzzerLoop.cpp:(.text+0x2e7a): undefined reference to `fuzzer::SM_visited_states'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::InputCorpus::AddToCorpus(std::vector<unsigned char, fuzzer::fuzzer_allocator<unsigned char> > const&, unsigned long, bool, bool, bool, std::chrono::duration<long, std::ratio<1l, 1000000l> >, std::vector<unsigned int, fuzzer::fuzzer_allocator<unsigned int> > const&, fuzzer::DataFlowTrace const&, fuzzer::InputInfo const*, unsigned long)':
FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm[_ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm]+0x1a3): undefined reference to `fuzzer::SM_visited_states'
/usr/bin/ld: FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm[_ZN6fuzzer11InputCorpus11AddToCorpusERKSt6vectorIhNS_16fuzzer_allocatorIhEEEmbbbNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEERKS1_IjNS2_IjEEERKNS_13DataFlowTraceEPKNS_9InputInfoEm]+0x1c4): undefined reference to `fuzzer::SM_added_states'
/usr/bin/ld: /lib/libsFuzzer.a(FuzzerLoop.o): in function `fuzzer::InputCorpus::UpdateCorpusDistribution(fuzzer::Random&)':
FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE[_ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE]+0x23a): undefined reference to `fuzzer::SM_root'
/usr/bin/ld: FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE[_ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE]+0x242): undefined reference to `fuzzer::StateMachine::sum_hits()'
/usr/bin/ld: FuzzerLoop.cpp:(.text._ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE[_ZN6fuzzer11InputCorpus24UpdateCorpusDistributionERNS_6RandomE]+0x252): undefined reference to `fuzzer::SM_num'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
